element_combinations = {
    frozenset(['🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🔥Fire']): '💨Steam',
    frozenset(['🌍Earth', '🔥Fire']): '🌋Lava',
    frozenset(['🌬️Wind', '🔥Fire']): '💨Smoke',
    frozenset(['🌋Volcano', '🔥Fire']): '🌋Lava',
    frozenset(['💨Steam', '🔥Fire']): '🚗Engine',
    frozenset(['🌋Lava', '🔥Fire']): '🌋Volcano',
    frozenset(['💨Smoke', '🔥Fire']): '🌋Volcano',
    frozenset(['🚗Engine', '🔥Fire']): '💨Steam',
    frozenset(['💧Water']): '🌊Lake',
    frozenset(['💧Water', '🌍Earth']): '🌱Plant',
    frozenset(['💧Water', '🌬️Wind']): '🌊Wave',
    frozenset(['💧Water', '🌋Volcano']): '🌋Lava',
    frozenset(['💧Water', '💨Steam']): '☁️Cloud',
    frozenset(['💧Water', '🌋Lava']): '🪨Stone',
    frozenset(['💧Water', '💨Smoke']): '🌫️Fog',
    frozenset(['💧Water', '🚗Engine']): '💨Steam',
    frozenset(['🌍Earth']): '🏔️Mountain',
    frozenset(['🌍Earth', '🌬️Wind']): '🌫️Dust',
    frozenset(['🌍Earth', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌍Earth']): '💩Mud',
    frozenset(['🌍Earth', '🌋Lava']): '🪨Stone',
    frozenset(['💨Smoke', '🌍Earth']): '🌋Volcano',
    frozenset(['🌍Earth', '🚗Engine']): '🚜Tractor',
    frozenset(['🌬️Wind']): '🌪️Tornado',
    frozenset(['🌬️Wind', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🌬️Wind']): '☁️Cloud',
    frozenset(['🌬️Wind', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌬️Wind']): '☁️Cloud',
    frozenset(['🌬️Wind', '🚗Engine']): '🌬️Windmill',
    frozenset(['🌋Volcano']): '🏔️Mountain',
    frozenset(['💨Steam', '🌋Volcano']): '🌋Lava',
    frozenset(['🌋Lava', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Smoke', '🌋Volcano']): '🌋Eruption',
    frozenset(['🚗Engine', '🌋Volcano']): '💨Steam',
    frozenset(['💨Steam']): '☁️Cloud',
    frozenset(['💨Steam', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Steam', '💨Smoke']): '☁️Cloud',
    frozenset(['💨Steam', '🚗Engine']): '🚂Train',
    frozenset(['🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌋Lava']): '🌋Volcano',
    frozenset(['🚗Engine', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke']): '☁️Cloud',
    frozenset(['💨Smoke', '🚗Engine']): '💨Steam',
    frozenset(['🚗Engine']): '🚀Rocket',
    frozenset(['🌊Lake', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🌊Lake']): '🌊Ocean',
    frozenset(['🌊Lake', '🌍Earth']): '🐊Swamp',
    frozenset(['🌊Lake', '🌬️Wind']): '⛈️Storm',
    frozenset(['🌊Lake', '🌋Volcano']): '🏝️Island',
    frozenset(['💨Steam', '🌊Lake']): '☁️Cloud',
    frozenset(['🌊Lake', '🌋Lava']): '🌋Volcano',
    frozenset(['🌊Lake', '💨Smoke']): '🌫️Fog',
    frozenset(['🌊Lake', '🚗Engine']): '🚤Boat',
    frozenset(['🌱Plant', '🔥Fire']): '💨Smoke',
    frozenset(['💧Water', '🌱Plant']): '🐊Swamp',
    frozenset(['🌍Earth', '🌱Plant']): '🌳Tree',
    frozenset(['🌬️Wind', '🌱Plant']): '🌼Dandelion',
    frozenset(['🌱Plant', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌱Plant']): '🍵Tea',
    frozenset(['🌋Lava', '🌱Plant']): '🌋Volcano',
    frozenset(['💨Smoke', '🌱Plant']): '🕯️Incense',
    frozenset(['🚗Engine', '🌱Plant']): '🚗Car',
    frozenset(['🌊Wave', '🔥Fire']): '💨Steam',
    frozenset(['💧Water', '🌊Wave']): '🌊Tsunami',
    frozenset(['🌊Wave', '🌍Earth']): '🏖️Sand',
    frozenset(['🌊Wave', '🌬️Wind']): '⛈️Storm',
    frozenset(['🌊Wave', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌊Wave']): '🏄Surf',
    frozenset(['🌊Wave', '🌋Lava']): '🪨Stone',
    frozenset(['💨Smoke', '🌊Wave']): '🏄Surf',
    frozenset(['🌊Wave', '🚗Engine']): '🌊Tsunami',
    frozenset(['🔥Fire', '☁️Cloud']): '⚡️Lightning',
    frozenset(['💧Water', '☁️Cloud']): '🌧️Rain',
    frozenset(['🌍Earth', '☁️Cloud']): '🌧️Rain',
    frozenset(['🌬️Wind', '☁️Cloud']): '⛈️Storm',
    frozenset(['🌋Volcano', '☁️Cloud']): '🌧️Rain',
    frozenset(['💨Steam', '☁️Cloud']): '🌧️Rain',
    frozenset(['🌋Lava', '☁️Cloud']): '🌋Volcano',
    frozenset(['💨Smoke', '☁️Cloud']): '🌫️Fog',
    frozenset(['🚗Engine', '☁️Cloud']): '✈️Jet',
    frozenset(['🪨Stone', '🔥Fire']): '🌋Lava',
    frozenset(['🪨Stone', '💧Water']): '🪨Rock',
    frozenset(['🪨Stone', '🌍Earth']): '🪨Rock',
    frozenset(['🪨Stone', '🌬️Wind']): '🏖️Sand',
    frozenset(['🪨Stone', '🌋Volcano']): '🌋Lava',
    frozenset(['🪨Stone', '💨Steam']): '🌋Geysir',
    frozenset(['🪨Stone', '🌋Lava']): '🔪Obsidian',
    frozenset(['🪨Stone', '💨Smoke']): '🗽Statue',
    frozenset(['🪨Stone', '🚗Engine']): '🚂Steamroller',
    frozenset(['⚡️Lightning', '🔥Fire']): '☀️Sun',
    frozenset(['💧Water', '⚡️Lightning']): '⚡️Electricity',
    frozenset(['🌍Earth', '⚡️Lightning']): '🌋Volcano',
    frozenset(['⚡️Lightning', '🌬️Wind']): '⛈️Storm',
    frozenset(['⚡️Lightning', '🌋Volcano']): '🌋Earthquake',
    frozenset(['💨Steam', '⚡️Lightning']): '⚡️Electricity',
    frozenset(['⚡️Lightning', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '⚡️Lightning']): '⛈️Thunder',
    frozenset(['⚡️Lightning', '🚗Engine']): '🚗Tesla',
    frozenset(['☀️Sun', '🔥Fire']): '☀️Solar',
    frozenset(['💧Water', '☀️Sun']): '🌈Rainbow',
    frozenset(['🌍Earth', '☀️Sun']): '🌱Plant',
    frozenset(['🌬️Wind', '☀️Sun']): '🌻Sunflower',
    frozenset(['☀️Sun', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '☀️Sun']): '🌈Rainbow',
    frozenset(['🌋Lava', '☀️Sun']): '🌋Volcano',
    frozenset(['💨Smoke', '☀️Sun']): '🌑Eclipse',
    frozenset(['🚗Engine', '☀️Sun']): '☀️Solar',
    frozenset(['🔥Fire', '☀️Solar']): '☀️Sun',
    frozenset(['💧Water', '☀️Solar']): '🌊Ocean',
    frozenset(['🌍Earth', '☀️Solar']): '🪐Planet',
    frozenset(['🌬️Wind', '☀️Solar']): '🌬️Windmill',
    frozenset(['🌋Volcano', '☀️Solar']): '☀️Sun',
    frozenset(['💨Steam', '☀️Solar']): '☀️Sun',
    frozenset(['🌋Lava', '☀️Solar']): '☀️Sun',
    frozenset(['💨Smoke', '☀️Solar']): '🌑Eclipse',
    frozenset(['🌫️Fog', '🔥Fire']): '💨Smoke',
    frozenset(['💧Water', '🌫️Fog']): '❄️Ice',
    frozenset(['🌫️Fog', '🌍Earth']): '🌫️Mist',
    frozenset(['🌫️Fog', '🌬️Wind']): '☁️Cloud',
    frozenset(['🌫️Fog', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🌫️Fog']): '☁️Cloud',
    frozenset(['🌫️Fog', '🌋Lava']): '🌋Volcano',
    frozenset(['🌫️Fog', '💨Smoke']): '☁️Cloud',
    frozenset(['🌫️Fog', '🚗Engine']): '💨Steam',
    frozenset(['🔥Fire', '🌊Ocean']): '💨Steam',
    frozenset(['💧Water', '🌊Ocean']): '🐟Fish',
    frozenset(['🌍Earth', '🌊Ocean']): '🏝️Island',
    frozenset(['🌬️Wind', '🌊Ocean']): '⛈️Storm',
    frozenset(['🌋Volcano', '🌊Ocean']): '🏝️Island',
    frozenset(['💨Steam', '🌊Ocean']): '☁️Cloud',
    frozenset(['🌋Lava', '🌊Ocean']): '🪨Stone',
    frozenset(['💨Smoke', '🌊Ocean']): '🌫️Fog',
    frozenset(['🚗Engine', '🌊Ocean']): '🚤Submarine',
    frozenset(['🐊Swamp', '🔥Fire']): '🐉Dragon',
    frozenset(['💧Water', '🐊Swamp']): '🌿Marsh',
    frozenset(['🌍Earth', '🐊Swamp']): '💩Mud',
    frozenset(['🌬️Wind', '🐊Swamp']): '🌫️Mist',
    frozenset(['🐊Swamp', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🐊Swamp']): '🐉Dragon',
    frozenset(['🐊Swamp', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🐊Swamp']): '🐉Dragon',
    frozenset(['🚗Engine', '🐊Swamp']): '🚂Train',
    frozenset(['🐉Dragon', '🔥Fire']): '🐉Dragon',
    frozenset(['💧Water', '🐉Dragon']): '🐍Sea  Serpent',
    frozenset(['🌍Earth', '🐉Dragon']): '🏔️Mountain',
    frozenset(['🌬️Wind', '🐉Dragon']): '🌪️Tornado',
    frozenset(['🐉Dragon', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🐉Dragon']): '🕯️Steampunk',
    frozenset(['🌋Lava', '🐉Dragon']): '🌋Volcano',
    frozenset(['💨Smoke', '🐉Dragon']): '🔥Fire',
    frozenset(['🚗Engine', '🐉Dragon']): '💨Steam',
    frozenset(['🌊Tsunami', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🌊Tsunami']): '🌊Ocean',
    frozenset(['🌍Earth', '🌊Tsunami']): '🏝️Island',
    frozenset(['🌬️Wind', '🌊Tsunami']): '🌀Hurricane',
    frozenset(['🌊Tsunami', '🌋Volcano']): '🌋Earthquake',
    frozenset(['💨Steam', '🌊Tsunami']): '🚢Titanic',
    frozenset(['🌋Lava', '🌊Tsunami']): '🌋Volcano',
    frozenset(['💨Smoke', '🌊Tsunami']): '🌋Volcano',
    frozenset(['🚗Engine', '🌊Tsunami']): '🌊Tsunami',
    frozenset(['🌧️Rain', '🔥Fire']): '🌈Rainbow',
    frozenset(['💧Water', '🌧️Rain']): '🌈Rainbow',
    frozenset(['🌧️Rain', '🌍Earth']): '🌱Plant',
    frozenset(['🌧️Rain', '🌬️Wind']): '⛈️Storm',
    frozenset(['🌧️Rain', '🌋Volcano']): '💩Mud',
    frozenset(['💨Steam', '🌧️Rain']): '☁️Cloud',
    frozenset(['🌧️Rain', '🌋Lava']): '🪨Stone',
    frozenset(['💨Smoke', '🌧️Rain']): '☁️Cloud',
    frozenset(['🌧️Rain', '🚗Engine']): '💨Steam',
    frozenset(['🌈Rainbow', '🔥Fire']): '🌧️Rain',
    frozenset(['💧Water', '🌈Rainbow']): '🌧️Rain',
    frozenset(['🌍Earth', '🌈Rainbow']): '🌧️Rain',
    frozenset(['🌈Rainbow', '🌬️Wind']): '🌧️Rain',
    frozenset(['🌈Rainbow', '🌋Volcano']): '🦄Unicorn',
    frozenset(['💨Steam', '🌈Rainbow']): '🌧️Rain',
    frozenset(['🌈Rainbow', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌈Rainbow']): '🌧️Rain',
    frozenset(['🪨Rock', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🪨Rock']): '🪨Stone',
    frozenset(['🌍Earth', '🪨Rock']): '🏔️Mountain',
    frozenset(['🌬️Wind', '🪨Rock']): '🌫️Dust',
    frozenset(['🪨Rock', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🪨Rock']): '🌋Geothermal',
    frozenset(['🪨Rock', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🪨Rock']): '🌋Volcano',
    frozenset(['🚗Engine', '🪨Rock']): '🪨Stone',
    frozenset(['⚡️Electricity', '🔥Fire']): '⚡️Lightning',
    frozenset(['💧Water', '⚡️Electricity']): '⚡️Lightning',
    frozenset(['🌍Earth', '⚡️Electricity']): '⚡️Lightning',
    frozenset(['🌬️Wind', '⚡️Electricity']): '⛈️Storm',
    frozenset(['⚡️Electricity', '🌋Volcano']): '⚡️Lightning',
    frozenset(['💨Steam', '⚡️Electricity']): '🚂Train',
    frozenset(['⚡️Electricity', '🌋Lava']): '🌋Magma',
    frozenset(['💨Smoke', '⚡️Electricity']): '⚡️Lightning',
    frozenset(['🚗Engine', '⚡️Electricity']): '🚗 Car',
    frozenset(['❄️Ice', '🔥Fire']): '💧Water',
    frozenset(['❄️Ice', '💧Water']): '🌊Iceberg',
    frozenset(['❄️Ice', '🌍Earth']): '❄️Snow',
    frozenset(['❄️Ice', '🌬️Wind']): '❄️Snow',
    frozenset(['❄️Ice', '🌋Volcano']): '🍦Ice  Cream',
    frozenset(['❄️Ice', '💨Steam']): '☁️Cloud',
    frozenset(['❄️Ice', '🌋Lava']): '🪨Stone',
    frozenset(['❄️Ice', '💨Smoke']): '🌫️Fog',
    frozenset(['❄️Ice', '🚗Engine']): '🧊Refrigerator',
    frozenset(['🐟Fish', '🔥Fire']): '🍣Sushi',
    frozenset(['💧Water', '🐟Fish']): '🐠Fishbowl',
    frozenset(['🌍Earth', '🐟Fish']): '🐳Whale',
    frozenset(['🌬️Wind', '🐟Fish']): '🐟Flying Fish',
    frozenset(['🐟Fish', '🌋Volcano']): '🍣Sushi',
    frozenset(['💨Steam', '🐟Fish']): '🍣Sushi',
    frozenset(['🌋Lava', '🐟Fish']): '🐢Salamander',
    frozenset(['💨Smoke', '🐟Fish']): '🍣Sushi',
    frozenset(['🚗Engine', '🐟Fish']): '🚤Submarine',
    frozenset(['🍣Sushi', '🔥Fire']): '🌶️Wasabi',
    frozenset(['💧Water', '🍣Sushi']): '🐟Fish',
    frozenset(['🍣Sushi', '🌍Earth']): '🍚Rice',
    frozenset(['🍣Sushi', '🌬️Wind']): '🐟Flying  Fish',
    frozenset(['🍣Sushi', '🌋Volcano']): '🍣Sushi',
    frozenset(['💨Steam', '🍣Sushi']): '🍣Sashimi',
    frozenset(['🍣Sushi', '🌋Lava']): '🌋Volcano',
    frozenset(['🍣Sushi', '🚗Engine']): '🚂Train',
    frozenset(['🌶️Wasabi', '🔥Fire']): '🔥Fire Breath',
    frozenset(['💧Water', '🌶️Wasabi']): '🍣Sushi',
    frozenset(['🌍Earth', '🌶️Wasabi']): '🍣Sushi',
    frozenset(['🌶️Wasabi', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🌶️Wasabi', '🌋Volcano']): '🔥Fire',
    frozenset(['💨Steam', '🌶️Wasabi']): '🍣Sushi',
    frozenset(['🌶️Wasabi', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌶️Wasabi']): '🤧Sneeze',
    frozenset(['🌶️Wasabi', '🚗Engine']): '🚀Rocket',
    frozenset(['🔥Fire', '🔥Fire Breath']): '🐉Dragon',
    frozenset(['💧Water', '🔥Fire Breath']): '💨Steam',
    frozenset(['🌍Earth', '🔥Fire Breath']): '🌋Volcano',
    frozenset(['🌬️Wind', '🔥Fire Breath']): '🔥Fire  Storm',
    frozenset(['🌋Volcano', '🔥Fire Breath']): '🌋Lava',
    frozenset(['💨Steam', '🔥Fire Breath']): '🌫️Steam  Breath',
    frozenset(['🌋Lava', '🔥Fire Breath']): '🌋Volcano',
    frozenset(['💨Smoke', '🔥Fire Breath']): '🔥Fire',
    frozenset(['🚗Engine', '🔥Fire Breath']): '🐉Dragon',
    frozenset(['🔥Fire', '🌿Marsh']): '🐊Swamp',
    frozenset(['💧Water', '🌿Marsh']): '🐊Swamp',
    frozenset(['🌍Earth', '🌿Marsh']): '🐊Swamp',
    frozenset(['🌬️Wind', '🌿Marsh']): '🌫️Mist',
    frozenset(['🌋Volcano', '🌿Marsh']): '🌋Lava',
    frozenset(['💨Steam', '🌿Marsh']): '🐊Swamp',
    frozenset(['🌋Lava', '🌿Marsh']): '🌋Volcano',
    frozenset(['💨Smoke', '🌿Marsh']): '🌫️Mist',
    frozenset(['🚗Engine', '🌿Marsh']): '🚂Train',
    frozenset(['🐍Sea Serpent', '🔥Fire']): '🐉Dragon',
    frozenset(['🐍Sea Serpent', '💧Water']): '🐋Leviathan',
    frozenset(['🐍Sea Serpent', '🌍Earth']): '🐋Leviathan',
    frozenset(['🐍Sea Serpent', '🌬️Wind']): '🐉Dragon',
    frozenset(['🐍Sea Serpent', '🌋Volcano']): '🐙Krakken',
    frozenset(['🐍Sea Serpent', '💨Steam']): '🐉Dragon',
    frozenset(['🐍Sea Serpent', '🌋Lava']): '🐉Dragon',
    frozenset(['🐍Sea Serpent', '💨Smoke']): '🐉Dragon',
    frozenset(['🐍Sea Serpent', '🚗Engine']): '🚤Submarine',
    frozenset(['🔥Fire', '🌊Iceberg']): '💧Water',
    frozenset(['💧Water', '🌊Iceberg']): '🌊Iceberg',
    frozenset(['🌍Earth', '🌊Iceberg']): '❄️Ice',
    frozenset(['🌬️Wind', '🌊Iceberg']): '❄️Snow',
    frozenset(['🌋Volcano', '🌊Iceberg']): '🍦Ice Cream',
    frozenset(['💨Steam', '🌊Iceberg']): '❄️Ice',
    frozenset(['🌋Lava', '🌊Iceberg']): '🌋Volcano',
    frozenset(['💨Smoke', '🌊Iceberg']): '☁️Cloud',
    frozenset(['🚗Engine', '🌊Iceberg']): '🚢Titanic',
    frozenset(['🔥Fire', '🐠Fishbowl']): '🐠Goldfish',
    frozenset(['💧Water', '🐠Fishbowl']): '🐟Fish',
    frozenset(['🌍Earth', '🐠Fishbowl']): '🐠Aquarium',
    frozenset(['🌬️Wind', '🐠Fishbowl']): '🌪️Tornado',
    frozenset(['🌋Volcano', '🐠Fishbowl']): '🐟Fish',
    frozenset(['💨Steam', '🐠Fishbowl']): '🐟Fish',
    frozenset(['🌋Lava', '🐠Fishbowl']): '🌋Volcano',
    frozenset(['💨Smoke', '🐠Fishbowl']): '💨Vapor',
    frozenset(['🚗Engine', '🐠Fishbowl']): '🐠Aquarium',
    frozenset(['🔥Fire', '🐠Goldfish']): '🐟Boiled Fish',
    frozenset(['💧Water', '🐠Goldfish']): '🐠Fishbowl',
    frozenset(['🌍Earth', '🐠Goldfish']): '🐸Pond',
    frozenset(['🌬️Wind', '🐠Goldfish']): '🪁Kite',
    frozenset(['🌋Volcano', '🐠Goldfish']): '🌋Lava',
    frozenset(['💨Steam', '🐠Goldfish']): '🐟Fish',
    frozenset(['🌋Lava', '🐠Goldfish']): '💛Gold',
    frozenset(['💨Smoke', '🐠Goldfish']): '💨Vapor',
    frozenset(['🚗Engine', '🐠Goldfish']): '🚗Car',
    frozenset(['🐟Boiled Fish', '🔥Fire']): '🐟Fish',
    frozenset(['💧Water', '🐟Boiled Fish']): '🍲Soup',
    frozenset(['🌍Earth', '🐟Boiled Fish']): '🌱Plant',
    frozenset(['🌬️Wind', '🐟Boiled Fish']): '🪁Kite',
    frozenset(['🐟Boiled Fish', '🌋Volcano']): '🍣Sushi',
    frozenset(['💨Steam', '🐟Boiled Fish']): '🍣Sushi',
    frozenset(['🌋Lava', '🐟Boiled Fish']): '🐟Fish',
    frozenset(['💨Smoke', '🐟Boiled Fish']): '🍣Sushi',
    frozenset(['🚗Engine', '🐟Boiled Fish']): '🚤Submarine',
    frozenset(['🐋Leviathan', '🔥Fire']): '🐉Dragon',
    frozenset(['💧Water', '🐋Leviathan']): '🐳Whale',
    frozenset(['🌍Earth', '🐋Leviathan']): '🌎Titan',
    frozenset(['🐋Leviathan', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🐋Leviathan', '🌋Volcano']): '🌋Krakatoa',
    frozenset(['💨Steam', '🐋Leviathan']): '🕯️Steampunk',
    frozenset(['🐋Leviathan', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🐋Leviathan']): '🐉Dragon',
    frozenset(['🐋Leviathan', '🚗Engine']): '🚤Submarine',
    frozenset(['🍲Soup', '🔥Fire']): '🌶️Chili',
    frozenset(['💧Water', '🍲Soup']): '🍲Soup',
    frozenset(['🍲Soup', '🌍Earth']): '🚢Titanic',
    frozenset(['🍲Soup', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🍲Soup', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🍲Soup']): '🍲Stew',
    frozenset(['🍲Soup', '🌋Lava']): '🍲Stone Soup',
    frozenset(['💨Smoke', '🍲Soup']): '🌫️Fog',
    frozenset(['🍲Soup', '🚗Engine']): '🚗Souped-up',
    frozenset(['🌶️Chili', '🔥Fire']): '🔥Hot',
    frozenset(['💧Water', '🌶️Chili']): '🍲Soup',
    frozenset(['🌶️Chili', '🌍Earth']): '🌶️Pepper',
    frozenset(['🌶️Chili', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🌶️Chili', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌶️Chili']): '🔥Hot',
    frozenset(['🌶️Chili', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌶️Chili']): '🔥Fire',
    frozenset(['🌶️Chili', '🚗Engine']): '🚀Rocket',
    frozenset(['🔥Hot', '🔥Fire']): '🔥Heat',
    frozenset(['💧Water', '🔥Hot']): '🍵Tea',
    frozenset(['🌍Earth', '🔥Hot']): '🌋Lava',
    frozenset(['🔥Hot', '🌬️Wind']): '🎈Hot  Air',
    frozenset(['🔥Hot', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🔥Hot']): '🧖\u200d♀Sauna',
    frozenset(['🔥Hot', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🔥Hot']): '🔥Fire',
    frozenset(['🔥Hot', '🚗Engine']): '💨Steam',
    frozenset(['🔥Heat', '🔥Fire']): '☀️Sun',
    frozenset(['💧Water', '🔥Heat']): '💨Steam',
    frozenset(['🌍Earth', '🔥Heat']): '🌋Lava',
    frozenset(['🌬️Wind', '🔥Heat']): '🎈Hot Air',
    frozenset(['🔥Heat', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🔥Heat']): '⚡️Energy',
    frozenset(['🌋Lava', '🔥Heat']): '🌋Volcano',
    frozenset(['💨Smoke', '🔥Heat']): '🔥Fire',
    frozenset(['🚗Engine', '🔥Heat']): '💨Steam',
    frozenset(['🔥Fire', '🐳Whale']): '🐉Dragon',
    frozenset(['💧Water', '🐳Whale']): '🌊Ocean',
    frozenset(['🌍Earth', '🐳Whale']): '🏝️Island',
    frozenset(['🌬️Wind', '🐳Whale']): '⛵️Sail',
    frozenset(['🌋Volcano', '🐳Whale']): '🏝️Island',
    frozenset(['💨Steam', '🐳Whale']): '🚤Submarine',
    frozenset(['🌋Lava', '🐳Whale']): '🌋Volcano',
    frozenset(['💨Smoke', '🐳Whale']): '💨Vape',
    frozenset(['🚗Engine', '🐳Whale']): '🚤Submarine',
    frozenset(['🔥Fire', '🍵Tea']): '🍵Chai',
    frozenset(['💧Water', '🍵Tea']): '🍵Tea',
    frozenset(['🌍Earth', '🍵Tea']): '🍵Teapot',
    frozenset(['🌬️Wind', '🍵Tea']): '🪁Kite',
    frozenset(['🌋Volcano', '🍵Tea']): '🌋Lava',
    frozenset(['💨Steam', '🍵Tea']): '🍵Teapot',
    frozenset(['🌋Lava', '🍵Tea']): '🌋Volcano',
    frozenset(['🚗Engine', '🍵Tea']): '🍵Teapot',
    frozenset(['🍵Chai', '🔥Fire']): '🍵Tea',
    frozenset(['💧Water', '🍵Chai']): '🍵Tea',
    frozenset(['🍵Chai', '🌍Earth']): '🍵Tea',
    frozenset(['🍵Chai', '🌬️Wind']): '🍵Tea',
    frozenset(['🍵Chai', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🍵Chai']): '🍵Tea',
    frozenset(['🍵Chai', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🍵Chai']): '🍵Tea',
    frozenset(['🍵Chai', '🚗Engine']): '🚂Train',
    frozenset(['🏔️Mountain', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🏔️Mountain']): '🌊Lake',
    frozenset(['🏔️Mountain', '🌍Earth']): '🌋Volcano',
    frozenset(['🏔️Mountain', '🌬️Wind']): '🌨Avalanche',
    frozenset(['🏔️Mountain', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🏔️Mountain']): '🌋Volcano',
    frozenset(['🏔️Mountain', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏔️Mountain']): '🌋Volcano',
    frozenset(['🏔️Mountain', '🚗Engine']): '🚂Train',
    frozenset(['🌫️Dust', '🔥Fire']): '🌋Ash',
    frozenset(['💧Water', '🌫️Dust']): '💩Mud',
    frozenset(['🌍Earth', '🌫️Dust']): '🪐Planet',
    frozenset(['🌫️Dust', '🌬️Wind']): '🌪️Sandstorm',
    frozenset(['🌫️Dust', '🌋Volcano']): '🌋Ash',
    frozenset(['💨Steam', '🌫️Dust']): '☁️Cloud',
    frozenset(['🌫️Dust', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌫️Dust']): '🌫️Dust',
    frozenset(['🌫️Dust', '🚗Engine']): '🧹Vacuum',
    frozenset(['💩Mud', '🔥Fire']): '🧱Brick',
    frozenset(['💧Water', '💩Mud']): '🐊Swamp',
    frozenset(['🌍Earth', '💩Mud']): '🏺Clay',
    frozenset(['💩Mud', '🌬️Wind']): '🌫️Dust',
    frozenset(['💩Mud', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💩Mud']): '🐊Swamp',
    frozenset(['💩Mud', '🌋Lava']): '🏺Clay',
    frozenset(['💨Smoke', '💩Mud']): '🐊Swamp',
    frozenset(['💩Mud', '🚗Engine']): '🚜Tractor',
    frozenset(['🌋Ash', '🔥Fire']): '🔥Phoenix',
    frozenset(['💧Water', '🌋Ash']): '💦Puddle',
    frozenset(['🌍Earth', '🌋Ash']): '🌱Soil',
    frozenset(['🌋Ash', '🌬️Wind']): '🌫️Dust',
    frozenset(['🌋Ash', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌋Ash']): '💨Smoke',
    frozenset(['🌋Ash', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌋Ash']): '🔥Fire',
    frozenset(['🌋Ash', '🚗Engine']): '💨Steam',
    frozenset(['🧱Brick', '🔥Fire']): '🧱Kiln',
    frozenset(['💧Water', '🧱Brick']): '🥃Glass',
    frozenset(['🌍Earth', '🧱Brick']): '🏠House',
    frozenset(['🌬️Wind', '🧱Brick']): '🏠House',
    frozenset(['🧱Brick', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🧱Brick']): '🚂Steam Engine',
    frozenset(['🌋Lava', '🧱Brick']): '🌋Volcano',
    frozenset(['💨Smoke', '🧱Brick']): '🏠Chimney',
    frozenset(['🚗Engine', '🧱Brick']): '🚂Train',
    frozenset(['🔥Fire', '🔥Phoenix']): '🌋Ash',
    frozenset(['💧Water', '🔥Phoenix']): '🌋Ash',
    frozenset(['🌍Earth', '🔥Phoenix']): '🔥Phoenix',
    frozenset(['🌬️Wind', '🔥Phoenix']): '🔥Fire',
    frozenset(['🌋Volcano', '🔥Phoenix']): '🐦Firebird',
    frozenset(['💨Steam', '🔥Phoenix']): '🕯️Steampunk',
    frozenset(['🌋Lava', '🔥Phoenix']): '🐦Firebird',
    frozenset(['💨Smoke', '🔥Phoenix']): '🌋Ash',
    frozenset(['🚗Engine', '🔥Phoenix']): '✈️Jet',
    frozenset(['🧱Kiln', '🔥Fire']): '🏺Pottery',
    frozenset(['💧Water', '🧱Kiln']): '🥃Glass',
    frozenset(['🌍Earth', '🧱Kiln']): '🏺Pottery',
    frozenset(['🧱Kiln', '🌬️Wind']): '🪁Kite',
    frozenset(['🧱Kiln', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🧱Kiln']): '🚗Engine',
    frozenset(['🧱Kiln', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🧱Kiln']): '🏺Pottery',
    frozenset(['🧱Kiln', '🚗Engine']): '🚂Steam  Engine',
    frozenset(['🏺Pottery', '🔥Fire']): '🏺Ceramic',
    frozenset(['💧Water', '🏺Pottery']): '🏺Vase',
    frozenset(['🌍Earth', '🏺Pottery']): '🏺Vase',
    frozenset(['🏺Pottery', '🌬️Wind']): '🏺Vase',
    frozenset(['🏺Pottery', '🌋Volcano']): '🏺Vase',
    frozenset(['💨Steam', '🏺Pottery']): '🍵Teapot',
    frozenset(['🏺Pottery', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏺Pottery']): '🏺Vase',
    frozenset(['🏺Pottery', '🚗Engine']): '🏺Vase',
    frozenset(['🏺Ceramic', '🔥Fire']): '🏺Pottery',
    frozenset(['💧Water', '🏺Ceramic']): '🥘Pot',
    frozenset(['🌍Earth', '🏺Ceramic']): '🥘Pot',
    frozenset(['🏺Ceramic', '🌬️Wind']): '🏺Pottery',
    frozenset(['🏺Ceramic', '🌋Volcano']): '🏺Clay',
    frozenset(['💨Steam', '🏺Ceramic']): '🍵Teapot',
    frozenset(['🏺Ceramic', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏺Ceramic']): '🏺Vase',
    frozenset(['🏺Ceramic', '🚗Engine']): '🚗Car',
    frozenset(['💦Puddle', '🔥Fire']): '💨Steam',
    frozenset(['💧Water', '💦Puddle']): '🐸Pond',
    frozenset(['🌍Earth', '💦Puddle']): '💩Mud',
    frozenset(['🌬️Wind', '💦Puddle']): '💦Puddle',
    frozenset(['💦Puddle', '🌋Volcano']): '💩Mud',
    frozenset(['💨Steam', '💦Puddle']): '☁️Cloud',
    frozenset(['🌋Lava', '💦Puddle']): '🪨Stone',
    frozenset(['💨Smoke', '💦Puddle']): '🪞Mirror',
    frozenset(['🚗Engine', '💦Puddle']): '💦Puddle',
    frozenset(['🥃Glass', '🔥Fire']): '🔍Lens',
    frozenset(['💧Water', '🥃Glass']): '🍷Wine',
    frozenset(['🥃Glass', '🌍Earth']): '🍾Bottle',
    frozenset(['🥃Glass', '🌬️Wind']): '🪟Window',
    frozenset(['🥃Glass', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🥃Glass']): '🪞Mirror',
    frozenset(['🥃Glass', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🥃Glass']): '🪞Mirror',
    frozenset(['🥃Glass', '🚗Engine']): '💨Windshield',
    frozenset(['🔍Lens', '🔥Fire']): '🔍Magnifying  Glass',
    frozenset(['💧Water', '🔍Lens']): '🔬Microscope',
    frozenset(['🔍Lens', '🌍Earth']): '🔭Telescope',
    frozenset(['🔍Lens', '🌬️Wind']): '🔭Telescope',
    frozenset(['🔍Lens', '🌋Volcano']): '📷Camera',
    frozenset(['💨Steam', '🔍Lens']): '📷Camera',
    frozenset(['🔍Lens', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🔍Lens']): '🪞Mirror',
    frozenset(['🔍Lens', '🚗Engine']): '🔭Telescope',
    frozenset(['🔍Magnifying  Glass', '🔥Fire']): '☀️Sun',
    frozenset(['🔍Magnifying  Glass', '💧Water']): '🐟Fish',
    frozenset(['🔍Magnifying  Glass', '🌍Earth']): '🦴Fossil',
    frozenset(['🔍Magnifying  Glass', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🔍Magnifying  Glass', '🌋Volcano']): '🌋Lava',
    frozenset(['🔍Magnifying  Glass', '💨Steam']): '🚂Steam Engine',
    frozenset(['🔍Magnifying  Glass', '🌋Lava']): '🌋Volcano',
    frozenset(['🔍Magnifying  Glass', '💨Smoke']): '🔥Fire',
    frozenset(['🔍Magnifying  Glass', '🚗Engine']): '🔭Telescope',
    frozenset(['🏺Vase', '🔥Fire']): '🌋Lava',
    frozenset(['🏺Vase', '💧Water']): '🌸Flower',
    frozenset(['🏺Vase', '🌍Earth']): '🥘Pot',
    frozenset(['🏺Vase', '🌬️Wind']): '🌬️Fan',
    frozenset(['🏺Vase', '🌋Volcano']): '💡Lava  Lamp',
    frozenset(['🏺Vase', '💨Steam']): '🍵Teapot',
    frozenset(['🏺Vase', '🌋Lava']): '🌋Volcano',
    frozenset(['🏺Vase', '💨Smoke']): '🧞\u200d♂Genie',
    frozenset(['🏺Vase', '🚗Engine']): '🚗Car',
    frozenset(['🔥Fire', '🥘Pot']): '🍳Cook',
    frozenset(['💧Water', '🥘Pot']): '🍲Soup',
    frozenset(['🌍Earth', '🥘Pot']): '🌱Plant',
    frozenset(['🌬️Wind', '🥘Pot']): '🪁Kite',
    frozenset(['🌋Volcano', '🥘Pot']): '🌋Lava',
    frozenset(['💨Steam', '🥘Pot']): '🍵Teapot',
    frozenset(['🌋Lava', '🥘Pot']): '🌋Volcano',
    frozenset(['💨Smoke', '🥘Pot']): '🌿Bong',
    frozenset(['🚗Engine', '🥘Pot']): '🍵Kettle',
    frozenset(['🍳Cook', '🔥Fire']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '💧Water']): '🍲Soup',
    frozenset(['🍳Cook', '🌍Earth']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '🌬️Wind']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '🌋Volcano']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '💨Steam']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '🌋Lava']): '🌋Volcano',
    frozenset(['🍳Cook', '💨Smoke']): '👨\u200d🍳Chef',
    frozenset(['🍳Cook', '🚗Engine']): '👨\u200d🍳Chef',
    frozenset(['🔥Fire', '👨\u200d🍳Chef']): '🍳Cook',
    frozenset(['💧Water', '👨\u200d🍳Chef']): '🍲Soup',
    frozenset(['🌍Earth', '👨\u200d🍳Chef']): '🍳Cook',
    frozenset(['🌬️Wind', '👨\u200d🍳Chef']): '🌪️Tornado',
    frozenset(['🌋Volcano', '👨\u200d🍳Chef']): '🍮Lava Cake',
    frozenset(['💨Steam', '👨\u200d🍳Chef']): '🍲Soup',
    frozenset(['🌋Lava', '👨\u200d🍳Chef']): '🌋Volcano',
    frozenset(['💨Smoke', '👨\u200d🍳Chef']): '🍖Barbecue',
    frozenset(['🚗Engine', '👨\u200d🍳Chef']): '🍳Cook',
    frozenset(['🔥Fire', '🐸Pond']): '🍲Soup',
    frozenset(['💧Water', '🐸Pond']): '🌊Lake',
    frozenset(['🌍Earth', '🐸Pond']): '🐊Swamp',
    frozenset(['🌬️Wind', '🐸Pond']): '🌫️Dust',
    frozenset(['🌋Volcano', '🐸Pond']): '🌋Geyser',
    frozenset(['💨Steam', '🐸Pond']): '🌫️Fog',
    frozenset(['🌋Lava', '🐸Pond']): '🪨Stone',
    frozenset(['💨Smoke', '🐸Pond']): '🌫️Fog',
    frozenset(['🚗Engine', '🐸Pond']): '💦Puddle',
    frozenset(['🍷Wine', '🔥Fire']): '🍷Alcohol',
    frozenset(['🍷Wine', '💧Water']): '💦Holy Water',
    frozenset(['🍷Wine', '🌍Earth']): '🍇Vineyard',
    frozenset(['🍷Wine', '🌬️Wind']): '🎈Balloon',
    frozenset(['🍷Wine', '🌋Volcano']): '🌋Lava',
    frozenset(['🍷Wine', '💨Steam']): '🍲Stew',
    frozenset(['🍷Wine', '🌋Lava']): '🌋Volcano',
    frozenset(['🍷Wine', '💨Smoke']): '🚬Smoker',
    frozenset(['🍷Wine', '🚗Engine']): '⛽Fuel',
    frozenset(['🍷Alcohol', '🔥Fire']): '🔥Burn',
    frozenset(['💧Water', '🍷Alcohol']): '🍷Wine',
    frozenset(['🍷Alcohol', '🌍Earth']): '🍇Vineyard',
    frozenset(['🍷Alcohol', '🌬️Wind']): '🍷Hangover',
    frozenset(['🍷Alcohol', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🍷Alcohol']): '🚂Steam  Engine',
    frozenset(['🍷Alcohol', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🍷Alcohol']): '🔥Fire',
    frozenset(['🍷Alcohol', '🚗Engine']): '⛽Fuel',
    frozenset(['🔥Burn', '🔥Fire']): '🌋Ash',
    frozenset(['🔥Burn', '💧Water']): '💨Steam',
    frozenset(['🔥Burn', '🌍Earth']): '🌋Volcano',
    frozenset(['🔥Burn', '🌬️Wind']): '🔥Fire',
    frozenset(['🔥Burn', '🌋Volcano']): '🌋Lava',
    frozenset(['🔥Burn', '💨Steam']): '🚗Engine',
    frozenset(['🔥Burn', '🌋Lava']): '🌋Volcano',
    frozenset(['🔥Burn', '💨Smoke']): '🔥Fire',
    frozenset(['🔥Burn', '🚗Engine']): '🔥Fire',
    frozenset(['🔬Microscope', '🔥Fire']): '🦠Virus',
    frozenset(['💧Water', '🔬Microscope']): '🔬Amoeba',
    frozenset(['🌍Earth', '🔬Microscope']): '🦠Bacteria',
    frozenset(['🌬️Wind', '🔬Microscope']): '🌪️Tornado',
    frozenset(['🔬Microscope', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🔬Microscope']): '🚂Steam  Engine',
    frozenset(['🔬Microscope', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🔬Microscope']): '💨Vapor',
    frozenset(['🚗Engine', '🔬Microscope']): '🔭Telescope',
    frozenset(['🦠Virus', '🔥Fire']): '🤒Flu',
    frozenset(['🦠Virus', '💧Water']): '🤒Sick',
    frozenset(['🦠Virus', '🌍Earth']): '🌱Life',
    frozenset(['🦠Virus', '🌬️Wind']): '🤒Flu',
    frozenset(['🦠Virus', '🌋Volcano']): '🌋Eruption',
    frozenset(['🦠Virus', '💨Steam']): '🧟Zombie',
    frozenset(['🦠Virus', '🌋Lava']): '🌋Volcano',
    frozenset(['🦠Virus', '💨Smoke']): '🤧Cough',
    frozenset(['🦠Virus', '🚗Engine']): '👾Hacker',
    frozenset(['🤒Flu', '🔥Fire']): '🤒Fever',
    frozenset(['🤒Flu', '💧Water']): '💦Fluoride',
    frozenset(['🤒Flu', '🌍Earth']): '💩Dirt',
    frozenset(['🤒Flu', '🌬️Wind']): '🤧Sneeze',
    frozenset(['🤒Flu', '🌋Volcano']): '🌋Eruption',
    frozenset(['🤒Flu', '💨Steam']): '🤒Sick',
    frozenset(['🤒Flu', '🌋Lava']): '🌋Volcano',
    frozenset(['🤒Flu', '💨Smoke']): '🤧Cough',
    frozenset(['🤒Flu', '🚗Engine']): '🚗Car',
    frozenset(['🤒Fever', '🔥Fire']): '👿Hell',
    frozenset(['💧Water', '🤒Fever']): '🍵Tea',
    frozenset(['🌍Earth', '🤒Fever']): '🌋Earthquake',
    frozenset(['🌬️Wind', '🤒Fever']): '🌀Hurricane',
    frozenset(['🤒Fever', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🤒Fever']): '🧖\u200d♀Sauna',
    frozenset(['🤒Fever', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🤒Fever']): '🔥Fire',
    frozenset(['🚗Engine', '🤒Fever']): '💨Steam',
    frozenset(['🔥Fire', '👿Hell']): '😈Devil',
    frozenset(['💧Water', '👿Hell']): '♨️Hot Spring',
    frozenset(['🌍Earth', '👿Hell']): '🌋Volcano',
    frozenset(['🌬️Wind', '👿Hell']): '😈Devil',
    frozenset(['🌋Volcano', '👿Hell']): '😈Satan',
    frozenset(['💨Steam', '👿Hell']): '🕯️Steampunk',
    frozenset(['🌋Lava', '👿Hell']): '🌋Volcano',
    frozenset(['💨Smoke', '👿Hell']): '🔥Fire',
    frozenset(['🚗Engine', '👿Hell']): '👷Engineer',
    frozenset(['😈Devil', '🔥Fire']): '👿Hell',
    frozenset(['💧Water', '😈Devil']): '👿Hell',
    frozenset(['🌍Earth', '😈Devil']): '👿Hell',
    frozenset(['🌬️Wind', '😈Devil']): '🌪️Tornado',
    frozenset(['😈Devil', '🌋Volcano']): '👿Hell',
    frozenset(['💨Steam', '😈Devil']): '🚂Train',
    frozenset(['😈Devil', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '😈Devil']): '👿Hell',
    frozenset(['🚗Engine', '😈Devil']): '💨Steam',
    frozenset(['🌸Flower', '🔥Fire']): '💨Smoke',
    frozenset(['💧Water', '🌸Flower']): '🌸Lily',
    frozenset(['🌸Flower', '🌍Earth']): '🌱Plant',
    frozenset(['🌸Flower', '🌬️Wind']): '🌼Dandelion',
    frozenset(['🌸Flower', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌸Flower']): '👃Perfume',
    frozenset(['🌸Flower', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌸Flower']): '🕯️Incense',
    frozenset(['🌸Flower', '🚗Engine']): '🚗Car',
    frozenset(['💦Holy Water', '🔥Fire']): '🧛Vampire',
    frozenset(['💧Water', '💦Holy Water']): '🍷Wine',
    frozenset(['💦Holy Water', '🌍Earth']): '💩Dirt',
    frozenset(['💦Holy Water', '🌬️Wind']): '👼Angel',
    frozenset(['💦Holy Water', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💦Holy Water']): '☁️Cloud',
    frozenset(['💦Holy Water', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '💦Holy Water']): '👼Angel',
    frozenset(['💦Holy Water', '🚗Engine']): '🧛Vampire',
    frozenset(['🧛Vampire', '🔥Fire']): '🌋Ash',
    frozenset(['💧Water', '🧛Vampire']): '🩸Blood',
    frozenset(['🌍Earth', '🧛Vampire']): '🧛Dracula',
    frozenset(['🌬️Wind', '🧛Vampire']): '🦇Bat',
    frozenset(['🧛Vampire', '🌋Volcano']): '🧛Dracula',
    frozenset(['💨Steam', '🧛Vampire']): '🧛Dracula',
    frozenset(['🧛Vampire', '🌋Lava']): '🦇Bat',
    frozenset(['💨Smoke', '🧛Vampire']): '🧛Dracula',
    frozenset(['🚗Engine', '🧛Vampire']): '🧛Vampire',
    frozenset(['🔬Amoeba', '🔥Fire']): '🔥Phoenix',
    frozenset(['💧Water', '🔬Amoeba']): '🐸Pond',
    frozenset(['🌍Earth', '🔬Amoeba']): '🌱Life',
    frozenset(['🌬️Wind', '🔬Amoeba']): '🦠Paramecium',
    frozenset(['🔬Amoeba', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🔬Amoeba']): '🍲Soup',
    frozenset(['🌋Lava', '🔬Amoeba']): '🌋Volcano',
    frozenset(['💨Smoke', '🔬Amoeba']): '☁️Cloud',
    frozenset(['🚗Engine', '🔬Amoeba']): '🚗Car',
    frozenset(['🔥Fire', '🤒Sick']): '🤒Fever',
    frozenset(['💧Water', '🤒Sick']): '💊Medicine',
    frozenset(['🌍Earth', '🤒Sick']): '💩Dirt',
    frozenset(['🌬️Wind', '🤒Sick']): '🌀Hurricane',
    frozenset(['🌋Volcano', '🤒Sick']): '🌋Eruption',
    frozenset(['💨Steam', '🤒Sick']): '🤒Fever',
    frozenset(['🌋Lava', '🤒Sick']): '🌋Volcano',
    frozenset(['💨Smoke', '🤒Sick']): '🚬Cigarette',
    frozenset(['🚗Engine', '🤒Sick']): '🔧Mechanic',
    frozenset(['💦Fluoride', '🔥Fire']): '🦷Toothpaste',
    frozenset(['💧Water', '💦Fluoride']): '🦷Toothpaste',
    frozenset(['🌍Earth', '💦Fluoride']): '🔲Fluoride',
    frozenset(['🌬️Wind', '💦Fluoride']): '💦Fluoride',
    frozenset(['💦Fluoride', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💦Fluoride']): '🦷Toothpaste',
    frozenset(['🌋Lava', '💦Fluoride']): '🔲Fluoride',
    frozenset(['💨Smoke', '💦Fluoride']): '🦷Toothpaste',
    frozenset(['🦷Toothpaste', '🔥Fire']): '🔥Fire  Breath',
    frozenset(['💧Water', '🦷Toothpaste']): '🦷Mouthwash',
    frozenset(['🌍Earth', '🦷Toothpaste']): '💩Dirt',
    frozenset(['🦷Toothpaste', '🌬️Wind']): '🌀Hurricane',
    frozenset(['🦷Toothpaste', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🦷Toothpaste']): '�Dentist',
    frozenset(['🦷Toothpaste', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🦷Toothpaste']): '💨Smoke',
    frozenset(['🦷Toothpaste', '🚗Engine']): '🦷Toothbrush',
    frozenset(['♨️Hot Spring', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '♨️Hot Spring']): '💨Steam',
    frozenset(['♨️Hot Spring', '🌍Earth']): '💩Mud',
    frozenset(['♨️Hot Spring', '🌬️Wind']): '☁️Cloud',
    frozenset(['♨️Hot Spring', '🌋Volcano']): '🌋Geyser',
    frozenset(['💨Steam', '♨️Hot Spring']): '🧖\u200d♀Sauna',
    frozenset(['♨️Hot Spring', '🌋Lava']): '🌋Volcano',
    frozenset(['♨️Hot Spring', '💨Smoke']): '💨Steam',
    frozenset(['♨️Hot Spring', '🚗Engine']): '🚂Steam  Engine',
    frozenset(['🌸Lily', '🔥Fire']): '🔥Phoenix',
    frozenset(['💧Water', '🌸Lily']): '🐸Pond',
    frozenset(['🌸Lily', '🌍Earth']): '🌸Flower',
    frozenset(['🌸Lily', '🌬️Wind']): '🌸Flower',
    frozenset(['🌸Lily', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌸Lily']): '🌸Flower',
    frozenset(['🌸Lily', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌸Lily']): '🕯️Incense',
    frozenset(['🌸Lily', '🚗Engine']): '🛳️Steamboat',
    frozenset(['🩸Blood', '🔥Fire']): '🧛Vampire',
    frozenset(['💧Water', '🩸Blood']): '🧛Vampire',
    frozenset(['🌍Earth', '🩸Blood']): '🧛Vampire',
    frozenset(['🩸Blood', '🌬️Wind']): '🧛Vampire',
    frozenset(['🩸Blood', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🩸Blood']): '🧛Vampire',
    frozenset(['🩸Blood', '🌋Lava']): '🧛Vampire',
    frozenset(['💨Smoke', '🩸Blood']): '🧛Vampire',
    frozenset(['🩸Blood', '🚗Engine']): '🧛Vampire',
    frozenset(['💊Medicine', '🔥Fire']): '💊Cure',
    frozenset(['💧Water', '💊Medicine']): '🧪Potion',
    frozenset(['💊Medicine', '🌍Earth']): '💩Dirt',
    frozenset(['💊Medicine', '🌬️Wind']): '🤧Sneeze',
    frozenset(['💊Medicine', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💊Medicine']): '🛳️Steamboat',
    frozenset(['💊Medicine', '🌋Lava']): '🌋Volcano',
    frozenset(['💊Medicine', '💨Smoke']): '🚬Cigarette',
    frozenset(['💊Medicine', '🚗Engine']): '💉Vaccine',
    frozenset(['🔥Fire', '💊Cure']): '🚒Firefighter',
    frozenset(['💧Water', '💊Cure']): '💊Medicine',
    frozenset(['🌍Earth', '💊Cure']): '💊Medicine',
    frozenset(['🌬️Wind', '💊Cure']): '💨Breeze',
    frozenset(['🌋Volcano', '💊Cure']): '🌋Lava',
    frozenset(['💨Steam', '💊Cure']): '🧖\u200d♀Sauna',
    frozenset(['🌋Lava', '💊Cure']): '🌋Volcano',
    frozenset(['💨Smoke', '💊Cure']): '💨Vapor',
    frozenset(['🚗Engine', '💊Cure']): '💨Steam',
    frozenset(['🚒Firefighter', '🔥Fire']): '🔥Fire',
    frozenset(['💧Water', '🚒Firefighter']): '🔥Fire',
    frozenset(['🚒Firefighter', '🌍Earth']): '🔥Fire',
    frozenset(['🚒Firefighter', '🌬️Wind']): '💨Smoke',
    frozenset(['🚒Firefighter', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🚒Firefighter']): '🚗Engine',
    frozenset(['🚒Firefighter', '🌋Lava']): '🌋Volcano',
    frozenset(['🚒Firefighter', '💨Smoke']): '🔥Fire',
    frozenset(['🚒Firefighter', '🚗Engine']): '🚒Fire Engine',
    frozenset(['🔥Fire', '🦷Mouthwash']): '🔥Fire Breath',
    frozenset(['💧Water', '🦷Mouthwash']): '🦷Mouthwash',
    frozenset(['🌍Earth', '🦷Mouthwash']): '💩Dirt',
    frozenset(['🌬️Wind', '🦷Mouthwash']): '🌪️Tornado',
    frozenset(['🌋Volcano', '🦷Mouthwash']): '🌋Eruption',
    frozenset(['💨Steam', '🦷Mouthwash']): '💨Vapor',
    frozenset(['🌋Lava', '🦷Mouthwash']): '🌋Volcano',
    frozenset(['💨Smoke', '🦷Mouthwash']): '💨Vapor',
    frozenset(['🚗Engine', '🦷Mouthwash']): '🚀Rocket',
    frozenset(['🧪Potion', '🔥Fire']): '🍵Elixir',
    frozenset(['💧Water', '🧪Potion']): '🍵Elixir',
    frozenset(['🌍Earth', '🧪Potion']): '🌱Plant',
    frozenset(['🧪Potion', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🧪Potion', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🧪Potion']): '🕯️Steampunk',
    frozenset(['🧪Potion', '🌋Lava']): '🌋Magma',
    frozenset(['💨Smoke', '🧪Potion']): '💨Vapor',
    frozenset(['🧪Potion', '🚗Engine']): '🚀Rocket',
    frozenset(['🔥Fire', '🍵Elixir']): '🧪Alchemy',
    frozenset(['💧Water', '🍵Elixir']): '🍷Wine',
    frozenset(['🌍Earth', '🍵Elixir']): '🌱Plant',
    frozenset(['🌬️Wind', '🍵Elixir']): '🌪️Tornado',
    frozenset(['🌋Volcano', '🍵Elixir']): '🌋Lava',
    frozenset(['💨Steam', '🍵Elixir']): '🚂Steam Engine',
    frozenset(['🌋Lava', '🍵Elixir']): '🌋Volcano',
    frozenset(['💨Smoke', '🍵Elixir']): '💨Vapor',
    frozenset(['🚗Engine', '🍵Elixir']): '💨Steam',
    frozenset(['🧪Alchemy', '🔥Fire']): '💥Explosion',
    frozenset(['💧Water', '🧪Alchemy']): '🌊Ocean',
    frozenset(['🧪Alchemy', '🌍Earth']): '🌱Soil',
    frozenset(['🧪Alchemy', '🌬️Wind']): '💨Air',
    frozenset(['🧪Alchemy', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🧪Alchemy']): '🕯️Steampunk',
    frozenset(['🧪Alchemy', '🌋Lava']): '🌋Volcano',
    frozenset(['🧪Alchemy', '💨Smoke']): '🔥Fire',
    frozenset(['🧪Alchemy', '🚗Engine']): '💨Steam',
    frozenset(['💥Explosion', '🔥Fire']): '🎆Fireworks',
    frozenset(['💧Water', '💥Explosion']): '🐟Fish',
    frozenset(['🌍Earth', '💥Explosion']): '🌋Volcano',
    frozenset(['💥Explosion', '🌬️Wind']): '🌪️Tornado',
    frozenset(['💥Explosion', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💥Explosion']): '🚂Steam Engine',
    frozenset(['💥Explosion', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '💥Explosion']): '🔥Fire',
    frozenset(['💥Explosion', '🚗Engine']): '🚀Rocket',
    frozenset(['🎆Fireworks', '🔥Fire']): '💥Explosion',
    frozenset(['💧Water', '🎆Fireworks']): '💦Splash',
    frozenset(['🌍Earth', '🎆Fireworks']): '🌋Volcano',
    frozenset(['🌬️Wind', '🎆Fireworks']): '🔥Fire',
    frozenset(['🎆Fireworks', '🌋Volcano']): '💥Explosion',
    frozenset(['💨Steam', '🎆Fireworks']): '🚀Rocket',
    frozenset(['🎆Fireworks', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🎆Fireworks']): '🔥Fire',
    frozenset(['🚗Engine', '🎆Fireworks']): '🚀Rocket',
    frozenset(['💦Splash', '🔥Fire']): '🎆Fireworks',
    frozenset(['💧Water', '💦Splash']): '🌊Wave',
    frozenset(['💦Splash', '🌍Earth']): '💩Mud',
    frozenset(['💦Splash', '🌬️Wind']): '🌧️Rain',
    frozenset(['💦Splash', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💦Splash']): '🌧️Rain',
    frozenset(['💦Splash', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '💦Splash']): '🔥Fire',
    frozenset(['💦Splash', '🚗Engine']): '🚗Car',
    frozenset(['🚜Tractor', '🔥Fire']): '🚜Tractor',
    frozenset(['💧Water', '🚜Tractor']): '🚤Boat',
    frozenset(['🚜Tractor', '🌍Earth']): '🐄Farm',
    frozenset(['🚜Tractor', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🚜Tractor', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🚜Tractor']): '🚂Train',
    frozenset(['🚜Tractor', '🌋Lava']): '🌋Volcano',
    frozenset(['🚜Tractor', '🚗Engine']): '🛢️Tank',
    frozenset(['🚤Boat', '🔥Fire']): '🚢Ship',
    frozenset(['💧Water', '🚤Boat']): '🚢Ship',
    frozenset(['🚤Boat', '🌍Earth']): '🏝️Island',
    frozenset(['🚤Boat', '🌬️Wind']): '⛵️Sail',
    frozenset(['🚤Boat', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🚤Boat']): '🛳️Steamboat',
    frozenset(['🚤Boat', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🚤Boat']): '🏴\u200d☠️Pirate',
    frozenset(['🚤Boat', '🚗Engine']): '🚢Ship',
    frozenset(['🚢Ship', '🔥Fire']): '🔫Cannon',
    frozenset(['💧Water', '🚢Ship']): '🚤Boat',
    frozenset(['🚢Ship', '🌍Earth']): '🏝️Island',
    frozenset(['🚢Ship', '🌬️Wind']): '⛵️Sail',
    frozenset(['🚢Ship', '🌋Volcano']): '🌊Atlantis',
    frozenset(['💨Steam', '🚢Ship']): '🚢Steamship',
    frozenset(['🚢Ship', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🚢Ship']): '🏴\u200d☠️Pirate',
    frozenset(['🚢Ship', '🚗Engine']): '🚢Steamship',
    frozenset(['🔫Cannon', '🔥Fire']): '💦Cannonball',
    frozenset(['💧Water', '🔫Cannon']): '🌊Tsunami',
    frozenset(['🌍Earth', '🔫Cannon']): '🌋Volcano',
    frozenset(['🌬️Wind', '🔫Cannon']): '🌪️Tornado',
    frozenset(['🔫Cannon', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🔫Cannon']): '🛳️Steamboat',
    frozenset(['🔫Cannon', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🔫Cannon']): '💣Gunpowder',
    frozenset(['🚗Engine', '🔫Cannon']): '🛢️Tank',
    frozenset(['🔥Fire', '💦Cannonball']): '🔫Cannon',
    frozenset(['💧Water', '💦Cannonball']): '🌊Tsunami',
    frozenset(['🌍Earth', '💦Cannonball']): '💫Meteor',
    frozenset(['🌬️Wind', '💦Cannonball']): '🌪️Tornado',
    frozenset(['🌋Volcano', '💦Cannonball']): '🌋Eruption',
    frozenset(['💨Steam', '💦Cannonball']): '🚂Steam  Engine',
    frozenset(['🌋Lava', '💦Cannonball']): '🌋Volcano',
    frozenset(['💨Smoke', '💦Cannonball']): '🎆Firework',
    frozenset(['🚗Engine', '💦Cannonball']): '🚂Train',
    frozenset(['🌳Tree', '🔥Fire']): '🌋Ash',
    frozenset(['💧Water', '🌳Tree']): '🌊River',
    frozenset(['🌳Tree', '🌍Earth']): '🌲Forest',
    frozenset(['🌳Tree', '🌬️Wind']): '🍃Leaf',
    frozenset(['🌳Tree', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌳Tree']): '☁️Cloud',
    frozenset(['🌳Tree', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌳Tree']): '🔥Fire',
    frozenset(['🌳Tree', '🚗Engine']): '🌲Wood',
    frozenset(['🌊River', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🌊River']): '🌊Lake',
    frozenset(['🌍Earth', '🌊River']): '⬇️Delta',
    frozenset(['🌬️Wind', '🌊River']): '🌧️Rain',
    frozenset(['🌊River', '🌋Volcano']): '🌋Geyser',
    frozenset(['💨Steam', '🌊River']): '☁️Cloud',
    frozenset(['🌊River', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌊River']): '🌫️Fog',
    frozenset(['🚗Engine', '🌊River']): '🚢Ship',
    frozenset(['🏖️Sand', '🔥Fire']): '🥃Glass',
    frozenset(['💧Water', '🏖️Sand']): '🏖️Beach',
    frozenset(['🌍Earth', '🏖️Sand']): '🏜️Desert',
    frozenset(['🌬️Wind', '🏖️Sand']): '🌵Dune',
    frozenset(['🏖️Sand', '🌋Volcano']): '🥃Glass',
    frozenset(['💨Steam', '🏖️Sand']): '🥃Glass',
    frozenset(['🏖️Sand', '🌋Lava']): '🥃Glass',
    frozenset(['💨Smoke', '🏖️Sand']): '🏜️Desert',
    frozenset(['🚗Engine', '🏖️Sand']): '🏖️Sandbox',
    frozenset(['🏖️Beach', '🔥Fire']): '☀️Sun',
    frozenset(['💧Water', '🏖️Beach']): '🌊Ocean',
    frozenset(['🏖️Beach', '🌍Earth']): '🏖️Sand',
    frozenset(['🏖️Beach', '🌬️Wind']): '🏖️Sand',
    frozenset(['🏖️Beach', '🌋Volcano']): '🌺Hawaii',
    frozenset(['💨Steam', '🏖️Beach']): '🧖\u200d♀Sauna',
    frozenset(['🏖️Beach', '🌋Lava']): '🌺Hawaii',
    frozenset(['🏖️Beach', '💨Smoke']): '🌋Volcano',
    frozenset(['🏖️Beach', '🚗Engine']): '🚢Ship',
    frozenset(['🔥Fire', '🪐Planet']): '🌋Volcano',
    frozenset(['💧Water', '🪐Planet']): '🌊Ocean',
    frozenset(['🌍Earth', '🪐Planet']): '🌙Moon',
    frozenset(['🌬️Wind', '🪐Planet']): '⛈️Storm',
    frozenset(['🌋Volcano', '🪐Planet']): '🌍Earth',
    frozenset(['💨Steam', '🪐Planet']): '🕯️Steampunk',
    frozenset(['🌋Lava', '🪐Planet']): '🌍Earth',
    frozenset(['💨Smoke', '🪐Planet']): '🌋Volcano',
    frozenset(['🚗Engine', '🪐Planet']): '🪐Saturn',
    frozenset(['🌫️Mist', '🔥Fire']): '🌫️Fog',
    frozenset(['💧Water', '🌫️Mist']): '🌫️Fog',
    frozenset(['🌍Earth', '🌫️Mist']): '🌫️Dust',
    frozenset(['🌫️Mist', '🌬️Wind']): '☁️Cloud',
    frozenset(['🌫️Mist', '🌋Volcano']): '☁️Cloud',
    frozenset(['💨Steam', '🌫️Mist']): '☁️Cloud',
    frozenset(['🌫️Mist', '🌋Lava']): '🪨Stone',
    frozenset(['💨Smoke', '🌫️Mist']): '🌫️Fog',
    frozenset(['🌫️Mist', '🚗Engine']): '💨Steam',
    frozenset(['🏝️Island', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🏝️Island']): '🚢Ship',
    frozenset(['🏝️Island', '🌍Earth']): '🌎Continent',
    frozenset(['🏝️Island', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🏝️Island', '🌋Volcano']): '🌺Hawaii',
    frozenset(['💨Steam', '🏝️Island']): '☁️Cloud',
    frozenset(['🏝️Island', '🌋Lava']): '🌋Volcano',
    frozenset(['🏝️Island', '💨Smoke']): '🌋Volcano',
    frozenset(['🏝️Island', '🚗Engine']): '🚂Train',
    frozenset(['❄️Snow', '🔥Fire']): '🌫️Fog',
    frozenset(['💧Water', '❄️Snow']): '❄️Ice',
    frozenset(['❄️Snow', '🌍Earth']): '☃️Snowman',
    frozenset(['❄️Snow', '🌬️Wind']): '❄️Blizzard',
    frozenset(['❄️Snow', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '❄️Snow']): '☁️Cloud',
    frozenset(['❄️Snow', '🌋Lava']): '🔪Obsidian',
    frozenset(['💨Smoke', '❄️Snow']): '🌫️Fog',
    frozenset(['❄️Snow', '🚗Engine']): '🏂Snowmobile',
    frozenset(['🍚Rice', '🔥Fire']): '🕯️Incense',
    frozenset(['💧Water', '🍚Rice']): '🍣Sushi',
    frozenset(['🌍Earth', '🍚Rice']): '🍀Paddy',
    frozenset(['🍚Rice', '🌬️Wind']): '🌬Fan',
    frozenset(['🍚Rice', '🌋Volcano']): '🍕Pizza',
    frozenset(['💨Steam', '🍚Rice']): '🍣Sushi',
    frozenset(['🍚Rice', '🌋Lava']): '🍣Sushi',
    frozenset(['💨Smoke', '🍚Rice']): '🕯️Incense',
    frozenset(['🍚Rice', '🚗Engine']): '🍚Rice Cooker',
    frozenset(['🐠Aquarium', '🔥Fire']): '🐟Fish',
    frozenset(['💧Water', '🐠Aquarium']): '🐟Fish',
    frozenset(['🌍Earth', '🐠Aquarium']): '🐟Fish',
    frozenset(['🐠Aquarium', '🌬️Wind']): '🐟Fish',
    frozenset(['🐠Aquarium', '🌋Volcano']): '🐟Fish',
    frozenset(['💨Steam', '🐠Aquarium']): '🐟Fish',
    frozenset(['🐠Aquarium', '🌋Lava']): '🐟Fish',
    frozenset(['💨Smoke', '🐠Aquarium']): '🐟Fish',
    frozenset(['🐠Aquarium', '🚗Engine']): '🚤Submarine',
    frozenset(['🔥Fire', '🌎Titan']): '🌍Atlas',
    frozenset(['💧Water', '🌎Titan']): '🌊Iceberg',
    frozenset(['🌍Earth', '🌎Titan']): '🌍Atlas',
    frozenset(['🌬️Wind', '🌎Titan']): '⚡️Zeus',
    frozenset(['🌋Volcano', '🌎Titan']): '🚢Titanic',
    frozenset(['💨Steam', '🌎Titan']): '🚢Titanic',
    frozenset(['🌋Lava', '🌎Titan']): '🌋Volcano',
    frozenset(['💨Smoke', '🌎Titan']): '🌍Atlas',
    frozenset(['🚗Engine', '🌎Titan']): '🚢Titanic',
    frozenset(['🔥Fire', '🚢Titanic']): '🌊Iceberg',
    frozenset(['💧Water', '🚢Titanic']): '🌊Iceberg',
    frozenset(['🌍Earth', '🚢Titanic']): '🌊Atlantis',
    frozenset(['🌬️Wind', '🚢Titanic']): '🌊Iceberg',
    frozenset(['🌋Volcano', '🚢Titanic']): '🌊Atlantis',
    frozenset(['💨Steam', '🚢Titanic']): '🌊Iceberg',
    frozenset(['🌋Lava', '🚢Titanic']): '🌋Volcano',
    frozenset(['💨Smoke', '🚢Titanic']): '🌊Iceberg',
    frozenset(['🚗Engine', '🚢Titanic']): '🌊Iceberg',
    frozenset(['🌶️Pepper', '🔥Fire']): '🌶️Spice',
    frozenset(['💧Water', '🌶️Pepper']): '🍲Soup',
    frozenset(['🌍Earth', '🌶️Pepper']): '🌶️Spice',
    frozenset(['🌶️Pepper', '🌬️Wind']): '🤧Sneeze',
    frozenset(['🌶️Pepper', '🌋Volcano']): '🍕Pepperoni',
    frozenset(['💨Steam', '🌶️Pepper']): '🥩Pepper Steak',
    frozenset(['🌶️Pepper', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌶️Pepper']): '🌶️Spice',
    frozenset(['🌶️Pepper', '🚗Engine']): '🌶️Chili',
    frozenset(['🍵Teapot', '🔥Fire']): '🍵Tea',
    frozenset(['💧Water', '🍵Teapot']): '🍵Tea',
    frozenset(['🌍Earth', '🍵Teapot']): '🍵Tea',
    frozenset(['🌬️Wind', '🍵Teapot']): '🍵Kettle',
    frozenset(['🍵Teapot', '🌋Volcano']): '🍵Tea',
    frozenset(['💨Steam', '🍵Teapot']): '🍵Tea',
    frozenset(['🍵Teapot', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🍵Teapot']): '🍵Tea',
    frozenset(['🚗Engine', '🍵Teapot']): '🚂Steam Engine',
    frozenset(['🏺Clay', '🔥Fire']): '🏺Pottery',
    frozenset(['💧Water', '🏺Clay']): '🏺Pottery',
    frozenset(['🌍Earth', '🏺Clay']): '🏺Pottery',
    frozenset(['🌬️Wind', '🏺Clay']): '🏺Pottery',
    frozenset(['🏺Clay', '🌋Volcano']): '🏺Ceramic',
    frozenset(['💨Steam', '🏺Clay']): '🏺Pottery',
    frozenset(['🏺Clay', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏺Clay']): '🏺Pottery',
    frozenset(['🚗Engine', '🏺Clay']): '🏺Pottery',
    frozenset(['🌱Soil', '🔥Fire']): '🌫️Dust',
    frozenset(['💧Water', '🌱Soil']): '💩Mud',
    frozenset(['🌍Earth', '🌱Soil']): '🌱Plant',
    frozenset(['🌱Soil', '🌬️Wind']): '🌫️Dust',
    frozenset(['🌱Soil', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌱Soil']): '💩Mud',
    frozenset(['🌱Soil', '🌋Lava']): '🪨Rock',
    frozenset(['💨Smoke', '🌱Soil']): '🌫️Dust',
    frozenset(['🌱Soil', '🚗Engine']): '🚜Tractor',
    frozenset(['🏠House', '🔥Fire']): '🏠Chimney',
    frozenset(['💧Water', '🏠House']): '🚢Ship',
    frozenset(['🌍Earth', '🏠House']): '🐄Farm',
    frozenset(['🏠House', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🏠House', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🏠House']): '🧖\u200d♀Sauna',
    frozenset(['🏠House', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏠House']): '🏠Chimney',
    frozenset(['🏠House', '🚗Engine']): '🚗Garage',
    frozenset(['🍾Bottle', '🔥Fire']): '🧞\u200d♂Genie',
    frozenset(['💧Water', '🍾Bottle']): '🍷Wine',
    frozenset(['🌍Earth', '🍾Bottle']): '🍷Wine',
    frozenset(['🍾Bottle', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🍾Bottle', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🍾Bottle']): '🛳️Steamboat',
    frozenset(['🍾Bottle', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🍾Bottle']): '🧞\u200d♂Genie',
    frozenset(['🍾Bottle', '🚗Engine']): '🚀Rocket',
    frozenset(['🔭Telescope', '🔥Fire']): '🔭Astronomer',
    frozenset(['💧Water', '🔭Telescope']): '🐟Fish',
    frozenset(['🔭Telescope', '🌍Earth']): '🌙Moon',
    frozenset(['🔭Telescope', '🌬️Wind']): '🪁Kite',
    frozenset(['🔭Telescope', '🌋Volcano']): '🌋Eruption',
    frozenset(['💨Steam', '🔭Telescope']): '🌌Space',
    frozenset(['🔭Telescope', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🔭Telescope']): '🔭Astronomer',
    frozenset(['🔭Telescope', '🚗Engine']): '🌌Hubble',
    frozenset(['🦴Fossil', '🔥Fire']): '🦖Dinosaur',
    frozenset(['💧Water', '🦴Fossil']): '🛢️Oil',
    frozenset(['🌍Earth', '🦴Fossil']): '🛢️Oil',
    frozenset(['🌬️Wind', '🦴Fossil']): '🌫️Dust',
    frozenset(['🦴Fossil', '🌋Volcano']): '🦖Dinosaur',
    frozenset(['💨Steam', '🦴Fossil']): '🦖Dinosaur',
    frozenset(['🦴Fossil', '🌋Lava']): '🦖Dinosaur',
    frozenset(['💨Smoke', '🦴Fossil']): '🦖Dinosaur',
    frozenset(['🚗Engine', '🦴Fossil']): '🦖Dinosaur',
    frozenset(['🍇Vineyard', '🔥Fire']): '🍷Wine',
    frozenset(['💧Water', '🍇Vineyard']): '🍷Wine',
    frozenset(['🌍Earth', '🍇Vineyard']): '🍷Wine',
    frozenset(['🍇Vineyard', '🌬️Wind']): '🍷Wine',
    frozenset(['🍇Vineyard', '🌋Volcano']): '🍷Wine',
    frozenset(['💨Steam', '🍇Vineyard']): '🍷Wine',
    frozenset(['🍇Vineyard', '🌋Lava']): '🍷Wine',
    frozenset(['💨Smoke', '🍇Vineyard']): '🍷Wine',
    frozenset(['🍇Vineyard', '🚗Engine']): '🍷Wine',
    frozenset(['🦠Bacteria', '🔥Fire']): '🧀Cheeze',
    frozenset(['💧Water', '🦠Bacteria']): '🤒Sick',
    frozenset(['🌍Earth', '🦠Bacteria']): '💩Dirt',
    frozenset(['🌬️Wind', '🦠Bacteria']): '🌫️Dust',
    frozenset(['🦠Bacteria', '🌋Volcano']): '🌱Life',
    frozenset(['💨Steam', '🦠Bacteria']): '🌱Life',
    frozenset(['🌋Lava', '🦠Bacteria']): '🌋Volcano',
    frozenset(['💨Smoke', '🦠Bacteria']): '🧀Cheeze',
    frozenset(['🚗Engine', '🦠Bacteria']): '🤖Robot',
    frozenset(['🌱Life', '🔥Fire']): '🧛Vampire',
    frozenset(['🌱Life', '💧Water']): '🐟Fish',
    frozenset(['🌱Life', '🌍Earth']): '👨Human',
    frozenset(['🌱Life', '🌬️Wind']): '💨Breeze',
    frozenset(['🌱Life', '🌋Volcano']): '🔥Phoenix',
    frozenset(['🌱Life', '💨Steam']): '⚡️Energy',
    frozenset(['🌱Life', '🌋Lava']): '🔥Phoenix',
    frozenset(['🌱Life', '💨Smoke']): '🧛Vampire',
    frozenset(['🌱Life', '🚗Engine']): '🤖Robot',
    frozenset(['💩Dirt', '🔥Fire']): '🧱Brick',
    frozenset(['💧Water', '💩Dirt']): '💩Mud',
    frozenset(['🌍Earth', '💩Dirt']): '🌱Soil',
    frozenset(['💩Dirt', '🌬️Wind']): '🌫️Dust',
    frozenset(['💩Dirt', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '💩Dirt']): '💩Mud',
    frozenset(['💩Dirt', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '💩Dirt']): '🌫️Dust',
    frozenset(['💩Dirt', '🚗Engine']): '🚜Tractor',
    frozenset(['🌋Earthquake', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🌋Earthquake']): '🌊Tsunami',
    frozenset(['🌍Earth', '🌋Earthquake']): '🏔️Mountain',
    frozenset(['🌬️Wind', '🌋Earthquake']): '🌪️Tornado',
    frozenset(['🌋Earthquake', '🌋Volcano']): '🌊Tsunami',
    frozenset(['💨Steam', '🌋Earthquake']): '🌋Volcano',
    frozenset(['🌋Lava', '🌋Earthquake']): '🌋Volcano',
    frozenset(['💨Smoke', '🌋Earthquake']): '🌋Volcano',
    frozenset(['🚗Engine', '🌋Earthquake']): '🌊Tremor',
    frozenset(['🧛Dracula', '🔥Fire']): '🧛Vampire',
    frozenset(['💧Water', '🧛Dracula']): '🩸Blood',
    frozenset(['🌍Earth', '🧛Dracula']): '🧛Vampire',
    frozenset(['🧛Dracula', '🌬️Wind']): '🦇Bat',
    frozenset(['🧛Dracula', '🌋Volcano']): '🧛Vampire',
    frozenset(['💨Steam', '🧛Dracula']): '🧛Vampire',
    frozenset(['🧛Dracula', '🌋Lava']): '🧛Vampire',
    frozenset(['💨Smoke', '🧛Dracula']): '🧛Vampire',
    frozenset(['🧛Dracula', '🚗Engine']): '🚂Train',
    frozenset(['🔲Fluorite', '🔥Fire']): '⚛️Fluorine',
    frozenset(['💧Water', '🔲Fluorite']): '⚛️Fluorine',
    frozenset(['🔲Fluorite', '🌍Earth']): '🔲Fluorite',
    frozenset(['🔲Fluorite', '🌬️Wind']): '🪁Kite',
    frozenset(['🐄Farm', '🔥Fire']): '🍖Barbecue',
    frozenset(['💧Water', '🐄Farm']): '🍚Rice',
    frozenset(['🌍Earth', '🐄Farm']): '🌾Field',
    frozenset(['🐄Farm', '🌬️Wind']): '🌬Windmill',
    frozenset(['🔥Fire', '💫Meteor']): '☀️Sun',
    frozenset(['💧Water', '💫Meteor']): '💫Meteorite',
    frozenset(['🌍Earth', '💫Meteor']): '🌙Moon',
    frozenset(['🌬️Wind', '💫Meteor']): '🌌Comet',
    frozenset(['🌲Forest', '🔥Fire']): '💨Smoke',
    frozenset(['💧Water', '🌲Forest']): '🐊Swamp',
    frozenset(['🌍Earth', '🌲Forest']): '🌳Tree',
    frozenset(['🌲Forest', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🌲Forest', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🌲Forest']): '🌧️Rain',
    frozenset(['🌲Forest', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🌲Forest']): '🔥Fire',
    frozenset(['🌲Forest', '🚗Engine']): '🚂Train',
    frozenset(['⬇️Delta', '🔥Fire']): '🗿Pyramid',
    frozenset(['💧Water', '⬇️Delta']): '🌊River',
    frozenset(['🌍Earth', '⬇️Delta']): '🌊River',
    frozenset(['⬇️Delta', '🌬️Wind']): '🌊River',
    frozenset(['🏜️Desert', '🔥Fire']): '🏖️Sand',
    frozenset(['💧Water', '🏜️Desert']): '🏜️Oasis',
    frozenset(['🌍Earth', '🏜️Desert']): '🏖️Sand',
    frozenset(['🏜️Desert', '🌬️Wind']): '🌪️Sandstorm',
    frozenset(['🏜️Desert', '🌋Volcano']): '🌵Cactus',
    frozenset(['💨Steam', '🏜️Desert']): '🏖️Sand',
    frozenset(['🏜️Desert', '🌋Lava']): '🌋Volcano',
    frozenset(['💨Smoke', '🏜️Desert']): '🌵Mirage',
    frozenset(['🏜️Desert', '🚗Engine']): '🚂Train',
    frozenset(['🌪️Tornado', '🔥Fire']): '🌋Volcano',
    frozenset(['🌪️Tornado', '💧Water']): '🌊Tsunami',
    frozenset(['🌪️Tornado', '🌍Earth']): '🌫️Dust',
    frozenset(['🌪️Tornado', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🌪️Tornado', '🌋Volcano']): '🌋Eruption',
    frozenset(['🌪️Tornado', '💨Steam']): '🌪️Tornado',
    frozenset(['🌪️Tornado', '🌋Lava']): '🌋Volcano',
    frozenset(['🌪️Tornado', '💨Smoke']): '🌋Volcano',
    frozenset(['🌪️Tornado', '🚗Engine']): '🌪️Tornado',
    frozenset(['🌋Eruption', '🔥Fire']): '🌋Volcano',
    frozenset(['🌋Eruption', '💧Water']): '🌋Lava',
    frozenset(['🌋Eruption', '🌍Earth']): '🌋Volcano',
    frozenset(['🌋Eruption', '🌬️Wind']): '🌋Volcano',
    frozenset(['🌋Eruption', '🌋Volcano']): '🌋Lava',
    frozenset(['🌋Eruption', '💨Steam']): '🌋Geyser',
    frozenset(['🌋Eruption', '🌋Lava']): '🌋Volcano',
    frozenset(['🌋Eruption', '💨Smoke']): '🌋Volcano',
    frozenset(['🌋Eruption', '🚗Engine']): '🌋Volcano',
    frozenset(['🌬Windmill', '🔥Fire']): '⚡️Energy',
    frozenset(['💧Water', '🌬Windmill']): '⚡️Energy',
    frozenset(['🌍Earth', '🌬Windmill']): '⚡️Electricity',
    frozenset(['🌬Windmill', '🌬️Wind']): '⚡️Electricity',
    frozenset(['⛈️Storm', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '⛈️Storm']): '🌧️Rain',
    frozenset(['⛈️Storm', '🌍Earth']): '🌪️Tornado',
    frozenset(['⛈️Storm', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🌼Dandelion', '🔥Fire']): '🌋Ash',
    frozenset(['💧Water', '🌼Dandelion']): '🍷Wine',
    frozenset(['🌼Dandelion', '🌍Earth']): '🌸Flower',
    frozenset(['🌼Dandelion', '🌬️Wind']): '🌱Seed',
    frozenset(['🌼Dandelion', '🌋Volcano']): '🎆Fireworks',
    frozenset(['💨Steam', '🌼Dandelion']): '🍵Tea',
    frozenset(['🌼Dandelion', '🌋Lava']): '🔥Fire',
    frozenset(['🌼Dandelion', '💨Smoke']): '🔥Fire',
    frozenset(['🌼Dandelion', '🚗Engine']): '🚁Helicopter',
    frozenset(['🌻Sunflower', '🔥Fire']): '☀️Sun',
    frozenset(['💧Water', '🌻Sunflower']): '☀️Sun',
    frozenset(['🌍Earth', '🌻Sunflower']): '☀️Sun',
    frozenset(['🌬️Wind', '🌻Sunflower']): '☀️Sun',
    frozenset(['🌻Sunflower', '🌋Volcano']): '☀️Sun',
    frozenset(['💨Steam', '🌻Sunflower']): '☀️Sun',
    frozenset(['🌋Lava', '🌻Sunflower']): '🌋Volcano',
    frozenset(['💨Smoke', '🌻Sunflower']): '💨Smoke Signal',
    frozenset(['🚗Engine', '🌻Sunflower']): '🛢️Oil',
    frozenset(['🌀Hurricane', '🔥Fire']): '🌋Volcano',
    frozenset(['💧Water', '🌀Hurricane']): '🌊Tsunami',
    frozenset(['🌀Hurricane', '🌍Earth']): '🌪️Tornado',
    frozenset(['🌀Hurricane', '🌬️Wind']): '🌪️Tornado',
    frozenset(['🐟Flying Fish', '🔥Fire']): '🐉Dragon',
    frozenset(['💧Water', '🐟Flying Fish']): '🐟Fish',
    frozenset(['🌍Earth', '🐟Flying Fish']): '🐦Bird',
    frozenset(['🌬️Wind', '🐟Flying Fish']): '✈️Airplane',
    frozenset(['🐟Flying Fish', '🌋Volcano']): '🐉Dragon',
    frozenset(['💨Steam', '🐟Flying Fish']): '✈️Jet',
    frozenset(['🌋Lava', '🐟Flying Fish']): '🐉Dragon',
    frozenset(['💨Smoke', '🐟Flying Fish']): '🐉Dragon',
    frozenset(['🚗Engine', '🐟Flying Fish']): '✈️Jet',
    frozenset(['🔥Fire', '🔥Fire Storm']): '🔥Fire',
    frozenset(['💧Water', '🔥Fire Storm']): '💨Steam',
    frozenset(['🌍Earth', '🔥Fire Storm']): '🌋Volcano',
    frozenset(['🌬️Wind', '🔥Fire Storm']): '🌪️Tornado',
    frozenset(['🪁Kite', '🔥Fire']): '🎆Fireworks',
    frozenset(['💧Water', '🪁Kite']): '🌬Wind',
    frozenset(['🪁Kite', '🌍Earth']): '💩Dirt',
    frozenset(['🪁Kite', '🌬️Wind']): '✈️Flying',
    frozenset(['🤖Roblox', '🔥Fire']): '🏰Fortnite',
    frozenset(['💧Water', '🤖Roblox']): '💻Program',
    frozenset(['🏰Minecraft', '🔥Fire']): '💣TNT',
    frozenset(['💧Water', '🏰Minecraft']): '💣TNT',
    frozenset(['🏰Minecraft', '🌍Earth']): '🕳️Cave',
    frozenset(['🏰Minecraft', '🌬️Wind']): '🛤️Minecart',
    frozenset(['🏰Minecraft', '🌋Volcano']): '🌋Lava',
    frozenset(['💨Steam', '🏰Minecraft']): '🏰Minecraft',
    frozenset(['🏰Minecraft', '🌋Lava']): '💣Creeper',
    frozenset(['🏰Minecraft', '💨Smoke']): '🔥Fire',
    frozenset(['🏰Minecraft', '🚗Engine']): '💣TNT',
}


import re

# Build a mapping from normalized names to emoji+name
def normalize_name(name):
    # Remove emoji and lowercase the rest
    return re.sub(r'[^\w\s]', '', name).strip().lower()

# Build the mapping from normalized name to emoji+name
normalized_to_full = {}
for combo in element_combinations.keys():
    for item in combo:
        norm = normalize_name(item)
        normalized_to_full[norm] = item

def get_combination_result(query):
    # Normalize input
    norm_query = [normalize_name(q) for q in query]
    # Map back to emoji+name
    try:
        full_query = [normalized_to_full[n] for n in norm_query]
    except KeyError:
        return "Element not found!"
    # Lookup
    result = element_combinations.get(frozenset(full_query))
    return result if result else "Combination not found!"

# # Example usage:
# print(get_combination_result(['fire', 'water']))  # Output: 💨Steam
# print(get_combination_result(['minecraft', 'wind']))  # Output: 💨Steam
# print(get_combination_result(['rice', 'laffva']))  # Output: 🌫️Dust