[project]
name = "week5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "langgraph>=0.6.7",
    "pydantic>=2.11.9",
    "pyjokes>=0.8.3",
    "streamlit>=1.49.1",
]
