[project]
name = "crewai-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.114.0",
    "ipykernel>=6.29.5",
    "langchain-google-genai>=2.1.3",
    "pip>=25.0.1",
]
